import {syncAudio} from '../rendering/assets.js';
import * as Core from '../core/rules.js';
import {game,$,$$,maps,panel,toast,tone,hud,confirmAction,closePanel} from '../systems/journey.js';
const readSave=k=>{try{return JSON.parse(localStorage.getItem(k))}catch{return null}};
function writeSave(k,v){try{localStorage.setItem(k,JSON.stringify(v));return true}catch{toast('無法儲存：瀏覽器儲存空間不足或已停用。');return false}}
function autoSave(){writeSave('seventh-autosave',{state:JSON.parse(JSON.stringify(game.state)),thumb:$('#world').toDataURL('image/png'),date:Date.now()})}
function validSave(s){return s&&[1,2].includes(s.version)&&Number.isInteger(s.day)&&s.day>=1&&s.day<=7&&Number.isInteger(s.map)&&s.map>=0&&s.map<=3&&Array.isArray(s.bag)&&s.bag.every(i=>Core.defs[i.key]&&Array.isArray(i.shape))&&Array.isArray(s.parts)}
function loadData(d){if(!validSave(d?.state)){toast('這份存檔無法讀取。');return}game.state={...Core.newState(),...JSON.parse(JSON.stringify(d.state))};game.state.flowers=Array.from({length:12},(_,i)=>typeof game.state.flowers[i]==='object'?game.state.flowers[i]:game.state.flowers[i]?{plantedDay:game.state.day-1}:null);migrateItems(game.state);game.state.started=true;game.mode='';game.selected=null;game.pending=null;game.craft=null;$('#overlay').hidden=true;$('#overlay').classList.remove('overtitle');$('#intro').hidden=true;game.keys={};game.target=null;hud();toast('已讀取旅程。');if(game.state.ended)game.actions.endGame();else if(game.state.day===7&&!game.state.soulTaken)game.actions.soulScene()}
function migrateItems(s){
 const older=s.version===1;s.version=2;
 for(const it of [...s.bag,...s.gifted]){const d=Core.defs[it.key];if(!d)continue;
  if(!it.originId){for(const key of ['grade','desc','name','unique','noGift','seedKind'])it[key]=d[key];
   if(older&&['nametag','scissors','poisonflower'].includes(it.key)){it.shape=d.shape.map(p=>[...p]);if(it.x>=0&&!Core.fits(s,it,it.x,it.y)){it.x=-1;it.y=-1;Core.placeFirst(s,it)}}
  }
  if(it.unique&&!s.uniqueCollected.includes(it.key))s.uniqueCollected.push(it.key);
 }
 // 已經進行的旅程不憑空增加信件；新遊戲從完整的四件物品開始。
}
function menu(){game.mode='menu';panel('放得下嗎？',`<div class="menuitems"><button data-menu="resume">繼續遊戲</button><button data-menu="save">存檔</button><button data-menu="load">讀檔</button><button data-menu="settings">設定</button><button data-menu="quit">結束遊戲</button><button data-menu="achievements">成就</button></div><p class="hint">時間仍然流動。20:00後返回營地，當晚便不再外出。</p>`);$$('[data-menu]').forEach(b=>b.onclick=()=>{let a=b.dataset.menu;if(a==='resume')closePanel();else if(a==='save'||a==='load')slots(a);else if(a==='settings')settings();else if(a==='achievements')game.actions.achievements();else confirmAction('回到旅途的起點？','未存檔的進度會遺失。你也可以先返回選單存檔。',()=>{game.mode='';$('#overlay').hidden=true;$('#intro').hidden=false;game.state.started=false})})}
function slots(action){if(!game.state.started)$('#overlay').classList.add('overtitle');game.mode=action;panel(action==='save'?'把今天夾進書頁':'翻開某一天',`<p class="hint">7 個共用存檔欄位，保存在目前瀏覽器。清除網站資料會刪除存檔。</p><div class="slots">${Array.from({length:7},(_,i)=>{let d=readSave('seventh-slot-'+i);return `<button class="slot" data-slot="${i}" aria-label="存檔欄位 ${i+1}${d?' 第'+d.state.day+'天':''}">${d?`<img src="${d.thumb}" alt="存檔時的地圖"><span>第 ${d.state.day} 天 · ${maps[d.state.map]}<small>　${new Date(d.date).toLocaleDateString('zh-TW')}</small></span>`:''}</button>`}).join('')}</div><div class="actions"><button id="slotback">返回</button></div>`);$$('[data-slot]').forEach(b=>b.onclick=()=>{let key='seventh-slot-'+b.dataset.slot,d=readSave(key);if(action==='save'){const save=()=>{if(writeSave(key,{state:JSON.parse(JSON.stringify(game.state)),thumb:$('#world').toDataURL('image/png'),date:Date.now()})){slots('save');toast('旅程已保存。')}};if(d)confirmAction('覆蓋這一頁？',`原有的第 ${d.state.day} 天存檔會被目前進度取代。`,save);else save()}else if(d)loadData(d);else toast('這一頁還是空白的。')});$('#slotback').onclick=()=>game.state.started?menu():closePanel()}
function settings(){game.mode='settings';panel('森林的聲音',`<div class="range"><label for="volume">環境音量</label><input id="volume" type="range" min="0" max="100" value="${Math.round(game.volume*100)}"></div><div class="actions"><button id="settingfull">切換全螢幕</button><button id="settingback">返回選單</button></div><p class="hint">WASD / 方向鍵移動，Shift 衝刺，F 互動，E 背包，R 旋轉。<br>也可點選地面行走，點選物品後再點空格放置。<br>1920 × 1080、16:9 等比縮放。建議使用電腦。</p>`);$('#volume').oninput=e=>{game.volume=Number(e.target.value)/100;writeSave('seventh-settings',{volume:game.volume});syncAudio(game.soundOn,game.volume);tone(392,.1)};$('#settingfull').onclick=$('#fullscreen').onclick;$('#settingback').onclick=menu}
export function initMenus(){Object.assign(game.actions,{menu,slots,autoSave});let p=readSave('seventh-settings');if(p&&Number.isFinite(p.volume))game.volume=p.volume}
